


  
// File: contracts/StarNftContract.sol
//SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "./AknetERC721A.sol";

contract GalaxyNftContract is AknetERC721A {
    constructor() AknetERC721A("Galaxy NFT", "galaxy"){}

    function contractURI() public pure returns (string memory) {
      return "https://aknet-contracts-metadata.fra1.digitaloceanspaces.com/contract-metadata.json";
    }
}
//*********************************************************************//
//*********************************************************************//  
//                                                                                                                               
//                AAA               KKKKKKKKK    KKKKKKKNNNNNNNN        NNNNNNNN        EEEEEEEEEEEEEEEEEEEEEETTTTTTTTTTTTTTTTTTTTTTT
//               A:::A              K:::::::K    K:::::KN:::::::N       N::::::N        E::::::::::::::::::::ET:::::::::::::::::::::T
//              A:::::A             K:::::::K    K:::::KN::::::::N      N::::::N        E::::::::::::::::::::ET:::::::::::::::::::::T
//             A:::::::A            K:::::::K   K::::::KN:::::::::N     N::::::N        EE::::::EEEEEEEEE::::ET:::::TT:::::::TT:::::T
//            A:::::::::A           KK::::::K  K:::::KKKN::::::::::N    N::::::N          E:::::E       EEEEEETTTTTT  T:::::T  TTTTTT
//           A:::::A:::::A            K:::::K K:::::K   N:::::::::::N   N::::::N          E:::::E                     T:::::T        
//          A:::::A A:::::A           K::::::K:::::K    N:::::::N::::N  N::::::N          E::::::EEEEEEEEEE           T:::::T        
//         A:::::A   A:::::A          K:::::::::::K     N::::::N N::::N N::::::N          E:::::::::::::::E           T:::::T        
//        A:::::A     A:::::A         K:::::::::::K     N::::::N  N::::N:::::::N          E:::::::::::::::E           T:::::T        
//       A:::::AAAAAAAAA:::::A        K::::::K:::::K    N::::::N   N:::::::::::N          E::::::EEEEEEEEEE           T:::::T        
//      A:::::::::::::::::::::A       K:::::K K:::::K   N::::::N    N::::::::::N          E:::::E                     T:::::T        
//     A:::::AAAAAAAAAAAAA:::::A    KK::::::K  K:::::KKKN::::::N     N:::::::::N          E:::::E       EEEEEE        T:::::T        
//    A:::::A             A:::::A   K:::::::K   K::::::KN::::::N      N::::::::N        EE::::::EEEEEEEE:::::E      TT:::::::TT      
//   A:::::A               A:::::A  K:::::::K    K:::::KN::::::N       N:::::::N ...... E::::::::::::::::::::E      T:::::::::T      
//  A:::::A                 A:::::A K:::::::K    K:::::KN::::::N        N::::::N .::::. E::::::::::::::::::::E      T:::::::::T      
// AAAAAAA                   AAAAAAAKKKKKKKKK    KKKKKKKNNNNNNNN         NNNNNNN ...... EEEEEEEEEEEEEEEEEEEEEE      TTTTTTTTTTT      
//                                                                                                                                                   
//  v0.0.1
//
//         This smart contract was generated by Akn.et
//            Aknet allows you to launch large scale 
//                      NFT projects!
//
//    AKNET is not responsible for the content of this contract and
//        hopes it is being used in a responsible and kind way.     
//*********************************************************************//                                                     
//*********************************************************************// 